import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import Image from "next/image";
import { signIn, signOut, useSession } from "next-auth/react";

import { api, RouterOutputs } from "~/utils/api";
import Footer from "~/components/Footer";
import { Header } from "~/components/Header";
import NewUser from "~/components/NewUser";
import { useState } from "react";

const Home: NextPage = () => {
  const {data: sessionData} = useSession();

  return (
    <>
      <Head>
        <title>A to Z Daycare</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        {
          sessionData?.user ? (
            <Content />
          ) : 
          (
            <SplashScreen />
          )
        }

      </main>
    </>
  );
};

type Provider = RouterOutputs["provider"]["get"];

const Content: React.FC = () => {
  const {data: sessionData} = useSession();
  const [provider, setProvider] = useState<Provider | null>(null);
  const {refetch: refetchProvider} = api.provider.get.useQuery(
    {providerId: ""},
    {onSuccess: (data) => {
      setProvider(data);
    }}  
  )

  const createProvider = api.provider.create.useMutation({
    onSuccess: () =>{
      void refetchProvider();
    }
  })
  
  return (
    <>
      {provider?.userId ? (
        <div>
          <Header displayName={provider.DaycareName}/>
        </div>
      )
      :(
        <NewUser name={sessionData?.user?.name ?? ""}
                 onSave={({name, address1, address2, address3, city, state, zip}) =>{
                    void createProvider.mutate({
                          providerName: name,
                          address1,
                          address2,
                          address3,
                          city,
                          state,
                          zip
                        })
                      }
                 }
        />
      
      )}
      <Footer />
    </>
  )
}

const SplashScreen: React.FC = () =>  {
  return (
    <>
      <div className="navbar text-primary-content shadow-2xl">
        A to Z Daycare
      </div>
      <div className="h-screen flex flex-col items-center space-y-10 ">
        <div className="h-screen flex items-center content-start mb-[20vh]" >
          <div className="card card-side glass shadow-xl ">
            <figure className="w-[60vh]">
              <img src="/SplashImage.jpg" alt="A To Z Daycare"  />
            </figure>
            <div className="card-body">
              <h2 className="card-title text-white text-b text-3xl">A-Z Daycare Services</h2>
              <p className="text-white text-xl w-[60vh] p-5">High-quality daycare services are essential to the well-being of families and communities. That's why we're passionate about helping daycare centers like yours achieve their goals and make a positive impact on the lives of children and families. </p>
              <div className="card-actions justify-end">
                <button className="btn btn-primary" onClick={() => void signIn()}>Login</button>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Footer />
    </>
  )
}

export default Home;

